---

- include: ucp-iptables.yml

- name: "Copy images to host"
  copy:
    src: "{{ ddc_images }}"
    dest: /tmp
  when: ddc_images is defined

- name: "Load images in Docker engine"
  command: docker load -i /tmp/{{ ddc_images }}
  when: ddc_images is defined

- name: "Add license file"
  copy:
    src: "docker_subscription.lic"
    dest: /tmp

- name: "Install primary UCP controller"
  command: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/docker_subscription.lic:/docker_subscription.lic -e UCP_ADMIN_PASSWORD={{ ucp_admin_password }} --name ucp docker/ucp:{{ ucp_version }} install --host-address {{ ansible_default_ipv4['address'] }} --san {{ ansible_fqdn }} --san {{ ucp_fqdn }}

- name: "Get UCP ID"
  shell: docker run --rm -i -v /var/run/docker.sock:/var/run/docker.sock --name ucp docker/ucp:{{ ucp_version }} id
  register: id

- name: "Backup CA"
  shell: docker run --rm -i -v /var/run/docker.sock:/var/run/docker.sock --name ucp docker/ucp:{{ ucp_version }} backup --id {{ id.stdout }} --root-ca-only --passphrase {{ ca_backup_pass }} > /tmp/ca_backup.tar

- name: "Copy CA backup"
  fetch: 
    src: /tmp/ca_backup.tar
    dest: /tmp/
    flat: yes

- name: "Restart docker engine"
  service:
    name: docker
    state: restarted

