---

# Include devicemapper parameters
- include_vars: "../vars/el-devicemapper.yml"

- set_fact:
    storage_driver: "devicemapper"

- name: "devicemapper: Install LVM2"
  yum:
    name: lvm2
    state: present

- name: "devicemapper: Create volume group"
  lvg:
    vg: docker
    pvs: "{{ dm_device }}"
    state: present

- name: "devicemapper: Create logical volume"
  lvol:
    lv: thinpool
    vg: docker
    size: 95%VG
    opts: "--thin"
    state: present

- name: "devicemapper: Add LVM Profile"
  copy:
    src: "docker-thinpool.profile"
    dest: /etc/lvm/profile
    owner: root
    group: root

- name: "devicemapper: Apply LVM Profile"
  command: lvchange --metadataprofile docker-thinpool docker/thinpool

