---

- set_fact:
    storage_driver: devicemapper
  when: storage_driver is not defined

# Configure devicemapper if EL < 7.2 or overlay not defined
- include: lvm-dm.yml
  when: ansible_distribution_version < "7.2" or storage_driver != "overlay"

# Update Python to avoid TLS errors EL < 7.2
- include: fix-tls.yml
  when: ansible_distribution_version < "7.2"

- name: "Install libselinux-python to allow file copy"
  yum:
    name: libselinux-python
    state: present

- name: "Add Docker yum repo"
  template: 
    src: docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root

- name: "Install Docker package"
  yum:
    name: docker-engine
    update_cache: yes
    state: installed

- name: "Ensure /etc/docker dir exists"
  file:
    path: /etc/docker
    state: directory

- name: "Configure Docker engine"
  template: 
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    force: no # don't overwrite if exists
    owner: root
    group: root

